spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config
          #search-locations: "file:///D://Spring_Boot_Microservices_workspace//config"
        git:
          uri: "https://github.com/Ansemw/Banking_Project_Config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071
